Rand uniform normal
mrpowers-io/spark-daria pull request #166
Opened 2024-10-07 03:57 UTC by zeotuan

2024-10-08 09:49 UTC, alfonsorr requested changes

2024-10-08 09:49 UTC, alfonsorr commented on .github/workflows/core-ci.yml
> +        spark: ["3.0.1", "3.1.3", "3.2.4", "3.3.4", "3.4.3", "3.5.3"]
Can you move this update to other pr?

2024-10-08 10:14 UTC, zeotuan commented on .github/workflows/core-ci.yml
> +        spark: ["3.0.1", "3.1.3", "3.2.4", "3.3.4", "3.4.3", "3.5.3"]
I was hoping we could finish #165 first before this then I will rebase this on top after

2024-10-08 10:20 UTC, alfonsorr commented on .github/workflows/core-ci.yml
> +        spark: ["3.0.1", "3.1.3", "3.2.4", "3.3.4", "3.4.3", "3.5.3"]
Sure, but make a pr with the changes of the versions of spark and in the sbt file in a pr so the pr only contains the real content, then you can rebase both branches.

2024-10-09 09:52 UTC, zeotuan commented on .github/workflows/core-ci.yml
> +        spark: ["3.0.1", "3.1.3", "3.2.4", "3.3.4", "3.4.3", "3.5.3"]
I removed the unrelated change and cleaned the commit

2024-10-24 11:07 UTC, merged